language: cpp
matrix:
  include: 
  - os: linux
    dist: xenial
    sudo: required
    addons:
      apt:
        sources:
          - sourceline: 'ppa:zhaofeng-shu33/liblemon'
          - sourceline: 'ppa:zhaofeng-shu33/gtest'
        packages:
          - liblemon-dev
          - liblemon1.3.1
          - libgtest-dev
          - libboost-all-dev
    
before_script:
  - cmake -DENABLE_TESTING=ON ../ 
  
script:
  - make
  - ./lgf_compute --filename test.lgf
  - ./test_mf
  - ./speed_test --parametric
  - ./speed_test
